version: '3.5'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    container_name: voting_system_postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  frontend:
    build: ./frontend
    container_name: voting_system_frontend
    ports:
      - '5173:5173'
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: voting_system_backend
    ports:
      - 3000:3000
    depends_on:
      - db
    volumes:
      - ./backend/src:/app/src

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: voting_system_backend_pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - '5050:80'
    depends_on:
      - db